language: java
install: true
sudo: false

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: build
      name: "Building"
      script: ./gradlew build
    - stage: release
      name: "Pushing to bintray"
      before_install: pwd && ls -l
      script: ./gradlew bintrayUpload -x test

after_success:
  - bash <(curl -s https://codecov.io/bash)