language: java
install: true
sudo: false

jdk:
  - openjdk11

services:
  - docker

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
  - name: snapshot
    if: branch == master AND type == push
  - name: release
    if: branch == release AND type == push
  - name: docker
    if: branch IN (master, release) AND type == push
  - name: heroku
    if: branch IN (master, release) AND type == push

jobs:
  include:
    - stage: build
      name: "Building, testing and sending codecov reports"
      script:
        - ./gradlew build
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: snapshot
      name: "Pushing to snapshot repo (artifactory)"
      script: ./gradlew build artifactoryPublish -x test -Dsnapshot=true

    - stage: release
      name: "Pushing to release repo (bintray)"
      script: ./gradlew build bintrayUpload -x test

    - stage: heroku
      name: "Deploy to Heroku"
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: vazHZvOHg7EoHjw9fKI2R223nZz4QYRP/dguDpXzGIL1gw3CDkFr+2r+N9/ii2HDkfcmUtOf6Q9ETfXGVKlPUE1yx3MVfUNZGyLD8HVf6OB8x/R9CCrgV0gkCogppmZrJNJ6eE5zMtGenrj6XZB5LLBYgEgCRQeS7Jtsm9ywyzJAGO6nsBomztj59FsR13Goim4Wi96496K8sYk/jkacuaStsaWxJ+7jpoTtXHdsfAZjroxhupaucl6aBeGdzuoAThgHT4XDYWdTN6TPWkuCVq9C3zi9eLBgo+WjC7fkxmcF24vAiNnn0tpWaJ3yslRNpIneGUQfXSPOmVNM2tkESU9WPTHCHh5bNfQ/2WZ01Tu6qrwV43df7HPRJfeROz80wgJvbI1IwI9yoXj3drdnM7/eSOYrwxbHlR3RYWSUf0yJYnlpKdIIvKMVhCiB/tiivd/+WILsHvPLqmBzBNeqytSAH64pjVqITWvoCqzbWzI3s9umH7n1sMtueuu/zFhNTeh3P3xZkzP+jPVKFoos55uG1TEyTIAZNk2gPrO1cddv07LU6j3v0NZR+OQaSeCFC/aVENJ3lnGqKBxWpaFdjoh50m3ouI4TpKhPV5UrL649igPDdQ2vOUfaDI3sWQcXBoyHmVdlJzmP1p0U5n2/4UnJdUjZUzdwn5EMTPSXHLE=
        app:
          master: barkoder-dev
          release: barkoder
        on:
          repo: maslick/barkoder
        run:
          - restart

    - stage: docker
      name: "Pushing docker image to Docker hub"
      script:
        - ./gradlew build createDockerfile -x test
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - VER=$TRAVIS_BRANCH-`git rev-parse --short HEAD`-build$TRAVIS_BUILD_NUMBER
        - docker build -t maslick/barkoder:$VER build/libs
        - docker tag maslick/barkoder:$VER maslick/barkoder
        - docker push maslick/barkoder:$VER
        - docker push maslick/barkoder
