language: java
install: true
sudo: false

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
  - name: release
    if: branch = master

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: release
      script: ./gradlew bintrayUpload -x test

after_success:
  - bash <(curl -s https://codecov.io/bash)