language: java
install: true
sudo: false

jdk:
  - openjdk11

services:
  - docker

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
  - name: snapshot
    if: branch == master AND type == push
  - name: release
    if: branch == release AND type == push
  - name: docker
    if: branch IN (master, release) AND type == push
  - name: heroku
    if: branch IN (master, release) AND type == push

jobs:
  include:
    - stage: build
      name: "Building, testing and sending codecov reports"
      script:
        - ./gradlew build
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: snapshot
      name: "Pushing to snapshot repo (artifactory)"
      script: ./gradlew build artifactoryPublish -x test -Dsnapshot=true

    - stage: release
      name: "Pushing to release repo (bintray)"
      script: ./gradlew build bintrayUpload -x test

    - stage: heroku
      name: "Deploy to Heroku"
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: iQOCSge+xvOyjqi+kkOT08TLeQDJDaZFhzVm9KmLUAuyBjwhup0CYk2BOXMEM0j8QAerQuUOsopY7if0juq5suvIzRS+lZ2fXPllK/UKipw1fGKfrz8daGGslZG05Y0H6m4sDDKbPFkgf8xkh8xXFys6VI8XEuzLYN4Q8Rumei8xpbtiRWCC1/p/+8rIl9TZ30U5aK99aniG/JVUV5xAqxoHnx3tu8xcGjJ17i8vp0Q6RvDIkQyj768IJPSYBVKeluP8MlFaSUSE4caK8pUAjmRBGMzbnd1Rt4E+6fRAd4SUyFjmI8k+JKTvlUKvBe4eFem85QUIe3Xqi4qlLOtSKwXk7dYID9B7yp/p92ty7UOcnk3qrpB0iGWSTmoi8X3Q1A3MnLBb1koFY6kXKbl1xhmqgsfojWZpX/XNkei/p0XACKyjhfxk27UX7GFZqPc6FdLGfwRGiaBNaBfWHSwu9j5FXbFw8MCHAc48eb5xXEdXz5Rkt7BnE2PYNfceo6WWNHJAI8o+SbUjwKOUoFD7QK/FoNO9MxxTRnm/bxYS6JXKcNok17DxGP7Y47jI1uFX1RAX8IjH5jcjeiQFvAZtIkrI3e+7MYbXLibbfoT/kpeJ21eJjS1V2ToaJJNJDjaLWDCZw6YKZN+COGETAEkpDphSyfXr6pdGb6zTidq4ZpA=
        app:
          master: barkoder-dev
          release: barkoder
        on:
          repo: maslick/barkoder
        run:
          - restart

    - stage: docker
      name: "Pushing docker image to Docker hub"
      script:
        - ./gradlew build createDockerfile -x test
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - VER=$TRAVIS_BRANCH-`git rev-parse --short HEAD`-build$TRAVIS_BUILD_NUMBER
        - docker build -t maslick/barkoder:$VER build/libs
        - docker tag maslick/barkoder:$VER maslick/barkoder
        - docker push maslick/barkoder:$VER
        - docker push maslick/barkoder
