version: '3'

services:
  web:
    image: maslick/barkoder-ui:master-3
    restart: on-failure
    environment:
      - KC_ENABLED=false
      - KC_URL=https://keycloak.io/auth
      - REALM=barkoder
      - CLIENT_ID=barkoder-web
      - KC_ROLE=craftroom
      - BACKEND_URL=http://192.168.64.12:7777
    ports:
      - "8080:80"

  barkoder:
    image: maslick/barkoder:master-141
    restart: on-failure
    environment:
      - PGHOST=db
      - PGDATABASE=barkoderdb
      - PGUSER=admin
      - PGPASSWORD=password
      - KC_ENABLED=false
      - KCHOST=https://keycloak.io
      - REALM=barkoder
      - CLIENT=barkoder-backend
      - CLIENT_SECRET=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx
      - CLIENT_ROLE=craftroom
    ports:
      - "7777:8080"
    depends_on:
      - db

  db:
    image: postgres:10
    restart: on-failure
    environment:
      POSTGRES_DB: barkoderdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgbarkoder:/var/lib/postgresql/data

volumes:
  pgbarkoder: